// web/src/pages/Providers.tsx
import { useEffect, useMemo, useState } from 'react'
import { toast } from 'sonner'
import { ExternalLink } from 'lucide-react'
import { PageHeader } from '@/components/page-header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { StatusBadge } from '@/components/status-badge'
import { Switch } from '@/components/ui/switch'
import { Separator } from '@/components/ui/separator'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from '@/components/ui/select'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/table'
import { providersApi, type Provider } from '@/lib/api'
import { channelSchemaTyped, type ProviderSchema } from '@/lib/providerDocs'

export default function Providers() {
  const [providers, setProviders] = useState<Provider[]>([])
  const [dialogOpen, setDialogOpen] = useState(false)
  const [form, setForm] = useState<Provider | null>(null)
  const [config, setConfig] = useState<Record<string, unknown>>({})
  const [saving, setSaving] = useState(false)
  const [testing, setTesting] = useState(false)

  const load = async () => {
    try {
      const data = await providersApi.list()
      setProviders(data.list)
    } catch (err) {
      toast.error((err as Error).message)
    }
  }

  useEffect(() => {
    load()
  }, [])

  const schema: ProviderSchema | null = useMemo(() => (form ? channelSchemaTyped(form.name) : null), [form])

  const openDialog = (row: Provider) => {
    setForm({ ...row, main_site: !!row.main_site, enabled: !!row.enabled })
    try {
      const parsed = row.config ? (JSON.parse(row.config) as Record<string, unknown>) : {}
      parsed.use_proxy = !!parsed.use_proxy
      setConfig(parsed)
    } catch {
      setConfig({ use_proxy: false })
    }
    setDialogOpen(true)
  }

  const copy = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text)
      toast.success('已复制')
    } catch {
      toast.warning('复制失败，请手动复制')
    }
  }

  const onTest = async () => {
    if (!form) return
    setTesting(true)
    try {
      const payload: Record<string, unknown> = {
        client_id: form.client_id,
        config: JSON.stringify(config)
      }
      if (form.client_secret) payload.client_secret = form.client_secret
      const data = await providersApi.test(form.name, payload)
      toast.success(data.message || '配置有效')
    } catch (err) {
      toast.error((err as Error).message)
    } finally {
      setTesting(false)
    }
  }

  const onSave = async () => {
    if (!form) return
    setSaving(true)
    try {
      const payload: Record<string, unknown> = {
        client_id: form.client_id,
        enabled: form.enabled,
        main_site: form.main_site,
        config: JSON.stringify(config)
      }
      if (form.client_secret) payload.client_secret = form.client_secret
      await providersApi.update(form.name, payload)
      toast.success('保存成功')
      setDialogOpen(false)
      load()
    } catch (err) {
      toast.error((err as Error).message)
    } finally {
      setSaving(false)
    }
  }

  return (
    <div>
      <PageHeader
        title="登录渠道"
        description="配置第三方登录渠道。启用且「应用于主站」的渠道会展示在主站登录页。"
      />

      <div className="overflow-hidden rounded-md border border-border bg-card">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-14">ID</TableHead>
              <TableHead>渠道</TableHead>
              <TableHead>ClientID / AppID</TableHead>
              <TableHead>回调地址</TableHead>
              <TableHead className="w-20">主站</TableHead>
              <TableHead className="w-20">状态</TableHead>
              <TableHead className="w-20 text-right">操作</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {providers.map((p) => (
              <TableRow key={p.id}>
                <TableCell className="text-muted-foreground">{p.id}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <span className="font-medium">{p.display_name}</span>
                    <Badge variant={p.category === 'enterprise' ? 'warning' : 'secondary'} className="font-normal">
                      {p.category === 'enterprise' ? '企业' : '社交'}
                    </Badge>
                    <span className="text-xs text-muted-foreground">{p.name}</span>
                  </div>
                </TableCell>
                <TableCell className="font-mono text-xs text-muted-foreground">{p.client_id || '-'}</TableCell>
                <TableCell className="max-w-[220px] truncate text-xs text-muted-foreground">
                  {p.name === 'wechat_miniprogram' ? '前端 code 登录，无需回调' : p.callback_url}
                </TableCell>
                <TableCell>
                  <StatusBadge status={p.main_site ? 'success' : 'muted'}>{p.main_site ? '启用' : '停用'}</StatusBadge>
                </TableCell>
                <TableCell>
                  <StatusBadge status={p.enabled ? 'success' : 'muted'}>{p.enabled ? '启用' : '禁用'}</StatusBadge>
                </TableCell>
                <TableCell className="text-right">
                  <Button variant="ghost" size="sm" onClick={() => openDialog(p)}>
                    配置
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-xl">
          <DialogHeader>
            <DialogTitle>配置「{form?.display_name}」渠道</DialogTitle>
            <DialogDescription>{schema?.tips}</DialogDescription>
          </DialogHeader>

          {schema && form && (
            <div className="grid gap-5">
              {schema.registerUrl && (
                <a
                  href={schema.registerUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1.5 text-sm text-foreground underline-offset-4 hover:underline"
                >
                  {schema.registerLabel || '接入地址'} <ExternalLink className="h-3.5 w-3.5" />
                </a>
              )}

              <div className="flex items-center justify-between rounded-md border border-border px-4 py-3">
                <span className="text-sm">启用渠道</span>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-muted-foreground">开启后该渠道可发起登录</span>
                  <Switch checked={form.enabled} onCheckedChange={(v) => setForm({ ...form, enabled: v })} />
                </div>
              </div>
              <div className="flex items-center justify-between rounded-md border border-border px-4 py-3">
                <span className="text-sm">应用于主站登录</span>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-muted-foreground">开启后展示在主站登录页</span>
                  <Switch checked={form.main_site} onCheckedChange={(v) => setForm({ ...form, main_site: v })} />
                </div>
              </div>

              <div className="space-y-1.5">
                <Label>{schema.idLabel}</Label>
                <Input value={form.client_id} onChange={(e) => setForm({ ...form, client_id: e.target.value })} placeholder={schema.idPlaceholder} />
              </div>
              <div className="space-y-1.5">
                <Label>{schema.secretLabel}</Label>
                <Input
                  type="password"
                  value={form.client_secret}
                  onChange={(e) => setForm({ ...form, client_secret: e.target.value })}
                  placeholder={form.client_secret ? '留空则不修改' : schema.secretPlaceholder}
                />
              </div>

              <div className="space-y-1.5">
                <Label>回调地址</Label>
                <div className="flex gap-2">
                  <Input value={form.callback_url} readOnly className="font-mono text-xs" />
                  <Button variant="outline" onClick={() => copy(form.callback_url)}>
                    复制
                  </Button>
                </div>
                <p className="text-xs text-muted-foreground">由系统根据 HOST 自动拼接，不支持自定义。</p>
              </div>

              {schema.configFields.length > 0 && (
                <div className="space-y-3">
                  <Separator />
                  <p className="text-sm font-medium">{schema.divider || '扩展配置'}</p>
                  {schema.configFields.map((f) => (
                    <div key={f.key} className="space-y-1.5">
                      <Label>{f.label}</Label>
                      {f.type === 'select' ? (
                        <Select
                          value={String(config[f.key] || '')}
                          onValueChange={(v) => setConfig({ ...config, [f.key]: v })}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="请选择" />
                          </SelectTrigger>
                          <SelectContent>
                            {(f.options || []).map((o) => (
                              <SelectItem key={o.value} value={o.value}>
                                {o.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      ) : f.type === 'textarea' ? (
                        <Textarea
                          value={String(config[f.key] || '')}
                          onChange={(e) => setConfig({ ...config, [f.key]: e.target.value })}
                          rows={f.rows || 5}
                          placeholder={f.placeholder}
                        />
                      ) : (
                        <Input
                          value={String(config[f.key] || '')}
                          onChange={(e) => setConfig({ ...config, [f.key]: e.target.value })}
                          placeholder={f.placeholder}
                        />
                      )}
                    </div>
                  ))}
                </div>
              )}

              {schema.supportProxy && (
                <div className="space-y-2">
                  <Separator />
                  <div className="flex items-center justify-between rounded-md border border-border px-4 py-3">
                    <span className="text-sm">使用代理</span>
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-muted-foreground">境外渠道建议开启（系统设置配置 SOCKS5）</span>
                      <Switch
                        checked={!!config.use_proxy}
                        onCheckedChange={(v) => setConfig({ ...config, use_proxy: v })}
                      />
                    </div>
                  </div>
                </div>
              )}

              {schema.notes.length > 0 && (
                <Alert variant="warning">
                  <AlertTitle>注意事项</AlertTitle>
                  <AlertDescription>
                    <ul className="list-disc space-y-1 pl-4">
                      {schema.notes.map((n, i) => (
                        <li key={i}>{n}</li>
                      ))}
                    </ul>
                  </AlertDescription>
                </Alert>
              )}
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>
              取消
            </Button>
            <Button variant="outline" onClick={onTest} disabled={testing}>
              {testing ? '测试中…' : '测试渠道'}
            </Button>
            <Button onClick={onSave} disabled={saving}>
              {saving ? '保存中…' : '保存'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// web/src/views/Providers.vue
<template>
  <el-card>
    <template #header>
      <div class="card-header">
        <span>第三方登录渠道</span>
        <span class="tip">配置登录渠道，登录页会自动展示已启用且「应用于主站」的渠道</span>
      </div>
    </template>

    <el-table :data="providers" border stripe>
      <el-table-column prop="id" label="ID" width="60" />
      <el-table-column label="渠道" min-width="140">
        <template #default="{ row }">
          <div class="provider-name">
            <span class="name">{{ row.display_name }}</span>
            <el-tag size="small" :type="row.category === 'enterprise' ? 'warning' : 'primary'">
              {{ row.category === 'enterprise' ? '企业' : '社交' }}
            </el-tag>
          </div>
          <div class="provider-key">{{ row.name }}</div>
        </template>
      </el-table-column>
      <el-table-column prop="client_id" label="ClientID / AppID" min-width="160" show-overflow-tooltip />
      <el-table-column label="回调地址" min-width="200">
        <template #default="{ row }">
          <span v-if="noCallback(row.name)" class="callback">前端 code 登录，无需回调</span>
          <span v-else class="callback">{{ row.callback_url }}</span>
        </template>
      </el-table-column>
      <el-table-column label="主站" width="70">
        <template #default="{ row }">
          <el-tag size="small" :type="row.main_site ? 'success' : 'info'">
            {{ row.main_site ? '启用' : '停用' }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="状态" width="80">
        <template #default="{ row }">
          <el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '启用' : '禁用' }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="操作" width="120" fixed="right">
        <template #default="{ row }">
          <el-button size="small" @click="openDialog(row)">配置</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="dialogVisible" :title="`配置「${form.display_name}」渠道`" width="600px">
      <el-alert type="info" :closable="false" class="tips">
        <div class="tips-body">
          <span class="tips-text">{{ schema.tips }}</span>
          <el-link v-if="schema.registerUrl" type="primary" :href="schema.registerUrl" target="_blank">
            {{ schema.registerLabel || '接入地址' }} →
          </el-link>
        </div>
      </el-alert>

      <el-form :model="form" label-width="130px" class="channel-form">
        <el-form-item label="启用">
          <el-switch v-model="form.enabled" />
          <span class="switch-tip">开启后该渠道可发起登录</span>
        </el-form-item>
        <el-form-item label="应用于主站登录">
          <el-switch v-model="form.main_site" />
          <span class="switch-tip">开启后展示在主站登录页</span>
        </el-form-item>

        <el-form-item :label="schema.idLabel">
          <el-input v-model="form.client_id" :placeholder="schema.idPlaceholder" />
        </el-form-item>
        <el-form-item :label="schema.secretLabel">
          <el-input v-model="form.client_secret" type="password" show-password
            :placeholder="form.client_secret ? '留空则不修改' : schema.secretPlaceholder" />
        </el-form-item>

        <el-form-item label="回调地址">
          <el-input :model-value="callbackUrl" readonly>
            <template #append>
              <el-button :data-clipboard-text="callbackUrl" @click="copyCallback">复制</el-button>
            </template>
          </el-input>
          <div class="field-tip">由系统根据 HOST 自动拼接，不支持自定义</div>
        </el-form-item>

        <template v-if="schema.configFields.length">
          <el-divider content-position="left">{{ schema.divider }}</el-divider>
          <el-form-item v-for="f in schema.configFields" :key="f.key" :label="f.label">
            <el-select v-if="f.type === 'select'" v-model="config[f.key]">
              <el-option v-for="o in f.options" :key="o.value" :label="o.label" :value="o.value" />
            </el-select>
            <el-input v-else-if="f.type === 'textarea'" v-model="config[f.key]" type="textarea"
              :rows="f.rows || 5" :placeholder="f.placeholder" />
            <el-input v-else v-model="config[f.key]" :placeholder="f.placeholder" />
          </el-form-item>
        </template>

        <template v-if="schema.supportProxy">
          <el-divider content-position="left">代理设置</el-divider>
          <el-form-item label="使用代理">
            <el-switch v-model="config.use_proxy" />
            <span class="switch-tip">开启后通过系统设置的 SOCKS5 代理访问该渠道接口（境外渠道建议开启）</span>
          </el-form-item>
        </template>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button :loading="testing" @click="onTest">测试渠道</el-button>
        <el-button type="primary" :loading="saving" @click="onSave">保存</el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { listProviders, updateProvider, testProvider } from '../api/modules'
import { channelSchema } from '../utils/providerDocs'

const providers = ref([])
const dialogVisible = ref(false)
const saving = ref(false)
const testing = ref(false)
const form = ref({})
const config = ref({})

const schema = computed(() => channelSchema(form.value.name))

const callbackUrl = computed(() => {
  if (!form.value.name) return ''
  return form.value.callback_url || `${window.location.origin}/api/oauth/${form.value.name}/callback`
})

onMounted(load)

function noCallback(name) {
  return name === 'wechat_miniprogram'
}

async function load() {
  const data = await listProviders()
  providers.value = data.list
}

function openDialog(row) {
  form.value = {
    ...row,
    client_secret: row.client_secret || '',
    main_site: !!row.main_site
  }
  try {
    config.value = row.config ? JSON.parse(row.config) : {}
  } catch (e) {
    config.value = {}
  }
  config.value.use_proxy = !!config.value.use_proxy
  dialogVisible.value = true
}

function copyCallback() {
  navigator.clipboard?.writeText(callbackUrl.value)
  ElMessage.success('回调地址已复制')
}

async function onTest() {
  testing.value = true
  try {
    const payload = {
      client_id: form.value.client_id,
      config: JSON.stringify(config.value)
    }
    if (form.value.client_secret) {
      payload.client_secret = form.value.client_secret
    }
    const data = await testProvider(form.value.name, payload)
    ElMessage.success(data.message || '配置有效')
  } finally {
    testing.value = false
  }
}

async function onSave() {
  saving.value = true
  try {
    const payload = {
      client_id: form.value.client_id,
      enabled: !!form.value.enabled,
      main_site: !!form.value.main_site,
      config: JSON.stringify(config.value)
    }
    if (form.value.client_secret) {
      payload.client_secret = form.value.client_secret
    }
    await updateProvider(form.value.name, payload)
    ElMessage.success('保存成功')
    dialogVisible.value = false
    load()
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.tip {
  font-size: 12px;
  color: #909399;
}
.provider-name {
  display: flex;
  align-items: center;
  gap: 8px;
}
.provider-name .name {
  font-weight: 600;
}
.provider-key {
  font-size: 12px;
  color: #909399;
}
.callback {
  font-size: 12px;
  color: #606266;
  word-break: break-all;
}
.tips {
  margin-bottom: 16px;
}
.tips-body {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
}
.tips-text {
  flex: 1;
  line-height: 1.6;
}
.channel-form .switch-tip {
  margin-left: 10px;
  font-size: 12px;
  color: #909399;
}
.field-tip {
  font-size: 12px;
  color: #909399;
  line-height: 1.5;
}
</style>
