// web/src/views/UserCenter.vue
<template>
  <el-card>
    <template #header>
      <div class="card-header">
        <span>用户中心</span>
      </div>
    </template>

    <el-tabs v-model="activeTab">
      <!-- 基本资料 -->
      <el-tab-pane label="基本资料" name="profile">
        <el-form :model="profile" label-width="100px" style="max-width: 560px">
          <el-form-item label="头像">
            <div class="avatar-row">
              <el-input v-model="profile.avatar" placeholder="头像图片地址（http/https）" clearable />
              <el-avatar v-if="profile.avatar" :src="profile.avatar" :size="40" class="avatar-preview" />
            </div>
          </el-form-item>
          <el-form-item label="昵称">
            <el-input v-model="profile.nickname" placeholder="请输入昵称" clearable />
          </el-form-item>
          <el-form-item label="用户名">
            <el-input v-model="profile.username" placeholder="登录用户名" clearable />
          </el-form-item>
          <el-form-item v-if="emailChanged" label="邮箱验证码">
            <div class="code-row">
              <el-input v-model="profile.email_code" placeholder="请输入验证码" clearable />
              <el-button :disabled="emailSending" @click="onSendCode('email')">
                {{ emailCountdown > 0 ? emailCountdown + 's' : '发送验证码' }}
              </el-button>
            </div>
          </el-form-item>
          <el-form-item label="邮箱">
            <el-input v-model="profile.email" placeholder="绑定邮箱" clearable />
          </el-form-item>
          <el-form-item v-if="phoneChanged" label="手机验证码">
            <div class="code-row">
              <el-input v-model="profile.phone_code" placeholder="请输入验证码" clearable />
              <el-button :disabled="phoneSending" @click="onSendCode('phone')">
                {{ phoneCountdown > 0 ? phoneCountdown + 's' : '发送验证码' }}
              </el-button>
            </div>
          </el-form-item>
          <el-form-item label="手机号">
            <el-input v-model="profile.phone" placeholder="绑定手机号" clearable />
          </el-form-item>
          <el-form-item>
            <el-button type="primary" :loading="saving" @click="onSaveProfile">保存</el-button>
          </el-form-item>
        </el-form>
      </el-tab-pane>

      <!-- 修改密码 -->
      <el-tab-pane label="修改密码" name="password">
        <el-form ref="pwdFormRef" :model="pwd" :rules="pwdRules" label-width="100px" style="max-width: 420px">
          <el-form-item v-if="userStore.userInfo?.password_set" label="原密码" prop="old_password">
            <el-input v-model="pwd.old_password" type="password" show-password placeholder="请输入原密码" />
          </el-form-item>
          <el-form-item label="新密码" prop="new_password">
            <el-input v-model="pwd.new_password" type="password" show-password placeholder="请输入新密码" />
          </el-form-item>
          <el-form-item label="确认密码" prop="confirm_password">
            <el-input v-model="pwd.confirm_password" type="password" show-password placeholder="请再次输入新密码" />
          </el-form-item>
          <el-form-item>
            <el-button type="primary" :loading="saving" @click="onChangePassword">修改密码</el-button>
          </el-form-item>
        </el-form>
      </el-tab-pane>

      <!-- 账号绑定 -->
      <el-tab-pane label="账号绑定" name="bindings">
        <div class="binding-tip">
          绑定后可使用第三方渠道直接登录，仅展示系统设置中允许的登录渠道。
        </div>
        <div v-for="p in bindings" :key="p.name" class="binding-item">
          <div class="binding-info">
            <el-avatar v-if="p.bound && p.avatar" :src="p.avatar" :size="36" />
            <div class="binding-name">
              <span class="provider-name">{{ p.display_name }}</span>
              <el-tag v-if="p.bound" size="small" type="success">已绑定</el-tag>
              <el-tag v-else size="small" type="info">未绑定</el-tag>
              <span v-if="p.bound && p.nickname" class="account-nick">{{ p.nickname }}</span>
            </div>
          </div>
          <el-button v-if="p.bound" type="danger" plain size="small" @click="onUnbind(p)">
            解绑
          </el-button>
          <el-button v-else type="primary" size="small" :loading="bindingLoading === p.name" @click="onBind(p)">
            绑定
          </el-button>
        </div>
        <el-empty v-if="bindings.length === 0" description="暂无可绑定的登录渠道" />
      </el-tab-pane>
    </el-tabs>
  </el-card>
</template>

<script setup>
import { reactive, ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useUserStore } from '../stores/user'
import {
  updateProfile, changePassword, myBindings, bindLogin, unbindLogin, sendCode
} from '../api/auth'

const route = useRoute()
const router = useRouter()
const userStore = useUserStore()

const activeTab = ref('profile')
const saving = ref(false)
const bindingLoading = ref('')
const bindings = ref([])

const emailSending = ref(false)
const phoneSending = ref(false)

const emailCountdown = ref(0)
const phoneCountdown = ref(0)

const profile = reactive({
  nickname: '',
  avatar: '',
  username: '',
  email: '',
  email_code: '',
  phone: '',
  phone_code: ''
})
const original = reactive({ email: '', phone: '' })
const emailChanged = computed(() => profile.email.trim() !== original.email)
const phoneChanged = computed(() => profile.phone.trim() !== original.phone)

const pwdFormRef = ref()
const pwd = reactive({ old_password: '', new_password: '', confirm_password: '' })
const pwdRules = {
  new_password: [{ required: true, message: '请输入新密码', trigger: 'blur' }],
  confirm_password: [
    { required: true, message: '请再次输入新密码', trigger: 'blur' },
    {
      validator: (_, value, callback) => {
        if (value !== pwd.new_password) {
          callback(new Error('两次输入的密码不一致'))
        } else {
          callback()
        }
      },
      trigger: 'blur'
    }
  ]
}

onMounted(() => {
  applyUser()
  loadBindings()
  const bind = route.query.bind
  if (bind === 'success') {
    ElMessage.success('第三方账号绑定成功')
    router.replace({ query: {} })
  } else if (bind === 'fail') {
    ElMessage.error(route.query.msg || '绑定失败')
    router.replace({ query: {} })
  }
})

function applyUser() {
  const u = userStore.userInfo || {}
  profile.nickname = u.nickname || ''
  profile.avatar = u.avatar || ''
  profile.username = u.username || ''
  profile.email = u.email || ''
  profile.phone = u.phone || ''
  original.email = u.email || ''
  original.phone = u.phone || ''
}

async function loadBindings() {
  try {
    bindings.value = await myBindings()
  } catch (e) {
    bindings.value = []
  }
}

async function onSaveProfile() {
  saving.value = true
  try {
    const payload = { ...profile }
    payload.email_code = emailChanged.value ? profile.email_code : ''
    payload.phone_code = phoneChanged.value ? profile.phone_code : ''
    const user = await updateProfile(payload)
    userStore.userInfo = user
    original.email = profile.email.trim()
    original.phone = profile.phone.trim()
    profile.email_code = ''
    profile.phone_code = ''
    ElMessage.success('保存成功')
  } finally {
    saving.value = false
  }
}

async function onChangePassword() {
  await pwdFormRef.value.validate()
  saving.value = true
  try {
    await changePassword({
      old_password: pwd.old_password,
      new_password: pwd.new_password
    })
    ElMessage.success('密码修改成功')
    pwd.old_password = ''
    pwd.new_password = ''
    pwd.confirm_password = ''
    await userStore.fetchUser()
  } finally {
    saving.value = false
  }
}

function onSendCode(field) {
  const account = field === 'email' ? profile.email.trim() : profile.phone.trim()
  if (!account) {
    ElMessage.warning(field === 'email' ? '请先填写邮箱' : '请先填写手机号')
    return
  }
  const sendingRef = field === 'email' ? emailSending : phoneSending
  const countdownRef = field === 'email' ? emailCountdown : phoneCountdown
  sendingRef.value = true
  sendCode({ scope: 'bind', account })
    .then(() => {
      countdownRef.value = 60
      const timer = setInterval(() => {
        countdownRef.value -= 1
        if (countdownRef.value <= 0) {
          clearInterval(timer)
          sendingRef.value = false
        }
      }, 1000)
    })
    .catch(() => {
      sendingRef.value = false
    })
}

async function onBind(p) {
  bindingLoading.value = p.name
  try {
    const data = await bindLogin(p.name)
    window.location.href = data.url
  } finally {
    bindingLoading.value = ''
  }
}

async function onUnbind(p) {
  await ElMessageBox.confirm(
    `确定解绑「${p.display_name}」吗？解绑后无法通过该渠道登录。`,
    '提示',
    { type: 'warning' }
  )
  await unbindLogin(p.name)
  ElMessage.success('解绑成功')
  loadBindings()
}
</script>

<style scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.avatar-row,
.code-row {
  display: flex;
  align-items: center;
  gap: 10px;
  width: 100%;
}
.avatar-preview {
  flex-shrink: 0;
}
.binding-tip {
  color: #909399;
  font-size: 13px;
  margin-bottom: 16px;
}
.binding-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 16px;
  border: 1px solid #ebeef5;
  border-radius: 6px;
  margin-bottom: 12px;
  max-width: 560px;
}
.binding-info {
  display: flex;
  align-items: center;
  gap: 12px;
}
.binding-name {
  display: flex;
  align-items: center;
  gap: 8px;
}
.provider-name {
  font-weight: 600;
}
.account-nick {
  color: #909399;
  font-size: 13px;
}
</style>

// web/src/pages/UserCenter.tsx
import { useEffect, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { toast } from 'sonner'
import { PageHeader } from '@/components/page-header'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { StatusBadge } from '@/components/status-badge'
import { UserAvatar } from '@/components/user-avatar'
import { Separator } from '@/components/ui/separator'
import { ConfirmDialog } from '@/components/ui/confirm'
import { authApi, type Binding } from '@/lib/api'
import { useUserStore } from '@/store/user'
import { cn } from '@/lib/utils'

type Tab = 'profile' | 'password' | 'bindings'

const TABS: { key: Tab; label: string }[] = [
  { key: 'profile', label: '基本资料' },
  { key: 'password', label: '修改密码' },
  { key: 'bindings', label: '账号绑定' }
]

export default function UserCenter() {
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const userInfo = useUserStore((s) => s.userInfo)
  const setUserInfo = useUserStore((s) => s.setUserInfo)
  const fetchUser = useUserStore((s) => s.fetchUser)

  const [tab, setTab] = useState<Tab>('profile')
  const [bindings, setBindings] = useState<Binding[]>([])

  // profile form
  const [nickname, setNickname] = useState('')
  const [avatar, setAvatar] = useState('')
  const [username, setUsername] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState('')
  const [emailCode, setEmailCode] = useState('')
  const [phoneCode, setPhoneCode] = useState('')
  const [origEmail, setOrigEmail] = useState('')
  const [origPhone, setOrigPhone] = useState('')
  const [saving, setSaving] = useState(false)
  const [sending, setSending] = useState<'email' | 'phone' | null>(null)
  const [countdown, setCountdown] = useState(0)
  const timerRef = useRef<number | null>(null)

  // password form
  const [oldPassword, setOldPassword] = useState('')
  const [newPassword, setNewPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')

  // bindings
  const [bindingLoading, setBindingLoading] = useState('')
  const [unbindTarget, setUnbindTarget] = useState<Binding | null>(null)

  useEffect(() => {
    applyUser()
    loadBindings()
    const bind = params.get('bind')
    if (bind === 'success') {
      toast.success('第三方账号绑定成功')
      navigate('/user-center', { replace: true })
    } else if (bind === 'fail') {
      toast.error(params.get('msg') || '绑定失败')
      navigate('/user-center', { replace: true })
    }
    return () => {
      if (timerRef.current) window.clearInterval(timerRef.current)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function applyUser() {
    const u = userInfo
    setNickname(u?.nickname || '')
    setAvatar(u?.avatar || '')
    setUsername(u?.username || '')
    setEmail(u?.email || '')
    setPhone(u?.phone || '')
    setOrigEmail(u?.email || '')
    setOrigPhone(u?.phone || '')
  }

  async function loadBindings() {
    try {
      setBindings(await authApi.bindings())
    } catch {
      setBindings([])
    }
  }

  const emailChanged = email.trim() !== origEmail
  const phoneChanged = phone.trim() !== origPhone

  const onSaveProfile = async () => {
    setSaving(true)
    try {
      const user = await authApi.updateProfile({
        nickname,
        avatar,
        username,
        email,
        email_code: emailChanged ? emailCode : '',
        phone,
        phone_code: phoneChanged ? phoneCode : ''
      })
      setUserInfo(user)
      setOrigEmail(email.trim())
      setOrigPhone(phone.trim())
      setEmailCode('')
      setPhoneCode('')
      toast.success('保存成功')
    } catch (err) {
      toast.error((err as Error).message)
    } finally {
      setSaving(false)
    }
  }

  const onSendCode = async (field: 'email' | 'phone') => {
    const account = (field === 'email' ? email : phone).trim()
    if (!account) {
      toast.warning(field === 'email' ? '请先填写邮箱' : '请先填写手机号')
      return
    }
    setSending(field)
    try {
      await authApi.sendCode({ scope: 'bind', account })
      toast.success('验证码已发送')
      setCountdown(60)
      timerRef.current = window.setInterval(() => {
        setCountdown((c) => {
          if (c <= 1 && timerRef.current) window.clearInterval(timerRef.current)
          return c - 1
        })
      }, 1000)
    } catch (err) {
      toast.error((err as Error).message)
    } finally {
      setSending(null)
    }
  }

  const onChangePassword = async () => {
    if (newPassword.length < 6) return toast.warning('密码长度不能少于 6 位')
    if (newPassword !== confirmPassword) return toast.warning('两次输入的密码不一致')
    setSaving(true)
    try {
      await authApi.changePassword({
        old_password: userInfo?.password_set ? oldPassword : undefined,
        new_password: newPassword
      })
      toast.success('密码修改成功')
      setOldPassword('')
      setNewPassword('')
      setConfirmPassword('')
      await fetchUser()
    } catch (err) {
      toast.error((err as Error).message)
    } finally {
      setSaving(false)
    }
  }

  const onBind = async (p: Binding) => {
    setBindingLoading(p.name)
    try {
      const data = await authApi.bindLogin(p.name)
      window.location.href = data.url
    } catch (err) {
      toast.error((err as Error).message)
    } finally {
      setBindingLoading('')
    }
  }

  const onUnbind = async () => {
    if (!unbindTarget) return
    try {
      await authApi.unbindLogin(unbindTarget.name)
      toast.success('解绑成功')
      setUnbindTarget(null)
      loadBindings()
    } catch (err) {
      toast.error((err as Error).message)
    }
  }

  return (
    <div>
      <PageHeader title="用户中心" description="管理个人资料、登录密码与第三方账号绑定。" />

      <div className="grid grid-cols-1 gap-10 lg:grid-cols-4">
        {/* 左侧导航 */}
        <aside className="lg:sticky lg:top-20 lg:self-start">
          <div className="mb-6 flex items-center gap-3">
            <UserAvatar avatar={userInfo?.avatar} email={userInfo?.email} username={userInfo?.nickname || userInfo?.username} size="lg" />
            <div>
              <div className="font-medium">{userInfo?.nickname || userInfo?.username}</div>
              <div className="text-xs text-muted-foreground">{userInfo?.email || userInfo?.username}</div>
            </div>
          </div>
          <nav className="flex gap-1 lg:flex-col">
            {TABS.map((t) => (
              <button
                key={t.key}
                onClick={() => setTab(t.key)}
                className={cn(
                  'rounded-md px-3 py-2 text-left text-sm transition-colors duration-150',
                  tab === t.key ? 'bg-accent font-medium text-foreground' : 'text-muted-foreground hover:bg-accent/60 hover:text-foreground'
                )}
              >
                {t.label}
              </button>
            ))}
          </nav>
        </aside>

        {/* 内容 */}
        <div className="lg:col-span-3">
          {tab === 'profile' && (
            <div className="max-w-xl space-y-5">
              <div className="flex items-center gap-4">
                <UserAvatar avatar={avatar} email={email} username={username} size="lg" />
                <div className="text-xs text-muted-foreground">头像支持：QQ 头像（QQ 邮箱）或 Gravatar</div>
              </div>
              <Field label="头像地址">
                <Input value={avatar} onChange={(e) => setAvatar(e.target.value)} placeholder="http(s) 图片地址，留空则自动使用 QQ 头像 / Gravatar" />
              </Field>
              <Field label="昵称">
                <Input value={nickname} onChange={(e) => setNickname(e.target.value)} placeholder="昵称" />
              </Field>
              <Field label="用户名">
                <Input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="登录用户名" />
              </Field>
              {emailChanged && (
                <Field label="邮箱验证码">
                  <div className="flex gap-2">
                    <Input value={emailCode} onChange={(e) => setEmailCode(e.target.value)} placeholder="验证码" />
                    <Button variant="outline" className="shrink-0" disabled={sending === 'email' || countdown > 0} onClick={() => onSendCode('email')}>
                      {countdown > 0 ? `${countdown}s` : '发送验证码'}
                    </Button>
                  </div>
                </Field>
              )}
              <Field label="邮箱">
                <Input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="绑定邮箱" />
              </Field>
              {phoneChanged && (
                <Field label="手机验证码">
                  <div className="flex gap-2">
                    <Input value={phoneCode} onChange={(e) => setPhoneCode(e.target.value)} placeholder="验证码" />
                    <Button variant="outline" className="shrink-0" disabled={sending === 'phone' || countdown > 0} onClick={() => onSendCode('phone')}>
                      {countdown > 0 ? `${countdown}s` : '发送验证码'}
                    </Button>
                  </div>
                </Field>
              )}
              <Field label="手机号">
                <Input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="绑定手机号" />
              </Field>
              <div className="pt-2">
                <Button onClick={onSaveProfile} disabled={saving}>
                  {saving ? '保存中…' : '保存'}
                </Button>
              </div>
            </div>
          )}

          {tab === 'password' && (
            <div className="max-w-md space-y-5">
              {userInfo?.password_set && (
                <Field label="原密码">
                  <Input type="password" value={oldPassword} onChange={(e) => setOldPassword(e.target.value)} placeholder="请输入原密码" />
                </Field>
              )}
              <Field label="新密码">
                <Input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} placeholder="不少于 6 位" />
              </Field>
              <Field label="确认密码">
                <Input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="请再次输入新密码" />
              </Field>
              <div className="pt-2">
                <Button onClick={onChangePassword} disabled={saving}>
                  {saving ? '修改中…' : '修改密码'}
                </Button>
              </div>
              {!userInfo?.password_set && (
                <p className="text-xs text-muted-foreground">当前账号未设置密码（第三方注册），可直接设置。</p>
              )}
            </div>
          )}

          {tab === 'bindings' && (
            <div className="max-w-xl">
              <p className="mb-4 text-sm text-muted-foreground">绑定后可使用第三方渠道直接登录本平台。</p>
              {bindings.length === 0 && <p className="text-sm text-muted-foreground">暂无可绑定的登录渠道。</p>}
              <div className="space-y-2">
                {bindings.map((p) => (
                  <div key={p.name} className="flex items-center justify-between rounded-md border border-border px-4 py-3">
                    <div className="flex items-center gap-3">
                      {p.bound && p.avatar ? (
                        <UserAvatar avatar={p.avatar} email={email} username={p.nickname} size="sm" />
                      ) : (
                        <span className="flex h-6 w-6 items-center justify-center rounded-full bg-muted text-xs font-medium">
                          {p.display_name.slice(0, 1)}
                        </span>
                      )}
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-medium">{p.display_name}</span>
                          <StatusBadge status={p.bound ? 'success' : 'muted'}>{p.bound ? '已绑定' : '未绑定'}</StatusBadge>
                        </div>
                        {p.bound && p.nickname && <div className="text-xs text-muted-foreground">{p.nickname}</div>}
                      </div>
                    </div>
                    {p.bound ? (
                      <Button variant="outline" size="sm" className="text-destructive" onClick={() => setUnbindTarget(p)}>
                        解绑
                      </Button>
                    ) : (
                      <Button size="sm" disabled={bindingLoading === p.name} onClick={() => onBind(p)}>
                        {bindingLoading === p.name ? '跳转中…' : '绑定'}
                      </Button>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      <Separator className="mt-12" />
      <p className="mt-4 text-xs text-muted-foreground">OauthGo · 统一授权管理平台</p>

      <ConfirmDialog
        open={!!unbindTarget}
        onOpenChange={(open) => !open && setUnbindTarget(null)}
        title={`确定解绑「${unbindTarget?.display_name}」吗？`}
        description="解绑后无法通过该渠道登录。若当前账号未设置密码且为最后一个绑定渠道，将无法解绑。"
        confirmText="解绑"
        destructive
        onConfirm={onUnbind}
      />
    </div>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <Label>{label}</Label>
      {children}
    </div>
  )
}
